version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    ports:
      - "9090:8080"
      - "50000:50000"
    volumes:
      - "$PWD/jenkins/volumn:/var/jenkins_home"
    networks:
      - net
  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - "$PWD/mysql/volumn:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
    networks:
      - net
  mongo:
    container_name: mongo
    image: mongodb/mongodb-community-server:6.0-ubi8 
    ports:
      - "27017:27017"
    volumes:
      - "$PWD/mongodb/volumn:/data/db"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    networks:
      - net
networks:
  net:
