version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    ports:
      - "9090:8080"
      - "50000:50000"
    volumes:
      - "$PWD/jenkins/volumn:/var/jenkins_home"
    networks:
      - net
  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - "$PWD/mysql/volumn:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
    networks:
      - net
  postgres:
    container_name: postgres
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
    networks:
      - net
    volumes: 
      - "$PWD/postgres/volumn:/var/lib/postgresql/data"
  mongo:                       #mongosh -u root -p 123456
    container_name: mongo
    image: mongodb/mongodb-community-server:6.0-ubi8 
    ports:
      - "27017:27017"
    volumes:
      - "$PWD/mongodb/volumn:/data/db"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    networks:
      - net

  # elasticsearch:
  #   image: elasticsearch:7.16.2
  #   container_name: elasticsearch
  #   volumes:
  #     - "$PWD/elasticSearch/volumn:/usr/share/elasticsearch/data"
  #   environment:
  #     ES_JAVA_OPTS: "-Xmx256m -Xms256m"
  #     discovery.type: single-node    
  #   ports:
  #   - '9200:9200'
  #   - '9300:9300'
  #   networks:
  #     - net

  # logstash:
  #   image: logstash:7.16.2
  #   container_name: logstash
  #   volumes:
  #     - "$PWD/logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf"
  #   depends_on:
  #     - elasticsearch
  #   ports:
  #     - '9600:9600'
  #   environment:
  #     LS_JAVA_OPTS: "-Xmx256m -Xms256m"    
  #   networks:
  #     - net

  # kibana:
  #   image: kibana:7.16.2
  #   container_name: kibana
  #   ports:
  #     - '5601:5601'
  #   environment:
  #     - ELASTICSEARCH_URL=http://elasticsearch:9200  
  #   depends_on:
  #     - elasticsearch  
  #   networks:
  #     - net
networks:
  net:
