version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    ports:
      - "9090:8080"
      - "50000:50000"
    volumes:
      - "$PWD/jenkins/volumn:/var/jenkins_home"
    networks:
      - net
  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - "$PWD/mysql/volumn:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
    networks:
      - net
networks:
  net:
